/* Copyright (c) 2022 Rick (rick 'at' gibbed 'dot' us)
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would
 *    be appreciated but is not required.
 *
 * 2. Altered source versions must be plainly marked as such, and must not
 *    be misrepresented as being the original software.
 *
 * 3. This notice may not be removed or altered from any source
 *    distribution.
 */

using System;

namespace Gibbed.LetUsClingTogether.FileFormats.Screenplay
{
    public static class TaskOpcodeHelpers
    {
        public static bool IsValid(this TaskOpcode opcode) => opcode switch
        {
            TaskOpcode.NoOperation0 => false,
            TaskOpcode.SetGlobalFlag => true,
            TaskOpcode.SetLocalFlag => true,
            TaskOpcode.ModifyApproval => true,
            TaskOpcode.PlatoonNow => true,
            TaskOpcode.ModifyGoth => true,
            TaskOpcode.ModifyDays => true,
            TaskOpcode.ModifyLoyaltyForBattlePartyLawfulUnits => true,
            TaskOpcode.ModifyLoyaltyForBattlePartyNeutralUnits => true,
            TaskOpcode.ModifyLoyaltyForBattlePartyChaosUnits => true,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterLawfulUnits => true,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterNeutralUnits => true,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterChaosUnits => true,
            TaskOpcode.SetHeroAlignment => true,
            TaskOpcode.ResetGlobalFlagsInCategory => true,
            TaskOpcode.SetPartyCharacterClan => true,
            TaskOpcode.ModifyRosterUnitsInClanLoyalty => true,
            TaskOpcode.SetPartyCharacterLoyalty => true,
            TaskOpcode.SetStrongpointChild => true,
            TaskOpcode.SetHeroClan => true,
            TaskOpcode.GetItem => true,
            TaskOpcode.Unknown15 => true,
            TaskOpcode.Unknown16 => true,
            TaskOpcode.Unknown17 => true,
            TaskOpcode.NoOperation24 => true,
            TaskOpcode.Unknown19 => true,
            TaskOpcode.SetPartyAllegiance => true,
            TaskOpcode.Unknown1B => true,
            TaskOpcode.Unknown1C => true,
            TaskOpcode.SetUnknownFlag => true,
            TaskOpcode.ResetUnknownFlags => true,
            TaskOpcode.SetPartyCharacterClass => true,
            TaskOpcode.RemoveItem => true,
            TaskOpcode.Unknown21 => true,
            TaskOpcode.Unknown22 => true,
            TaskOpcode.Unknown23 => true,
            TaskOpcode.Unknown24 => true,
            TaskOpcode.NoOperation37 => false,
            TaskOpcode.NoOperation38 => false,
            TaskOpcode.NoOperation39 => false,
            TaskOpcode.NoOperation40 => false,
            TaskOpcode.NoOperation41 => false,
            TaskOpcode.NoOperation42 => false,
            TaskOpcode.NoOperation43 => false,
            TaskOpcode.NoOperation44 => false,
            TaskOpcode.NoOperation45 => false,
            TaskOpcode.NoOperation46 => false,
            TaskOpcode.NoOperation47 => false,
            TaskOpcode.CompareGlobalFlag => true,
            TaskOpcode.CompareLocalFlag => true,
            TaskOpcode.CompareStrongpoint => true,
            TaskOpcode.CompareBattleActiveCharacter => true,
            TaskOpcode.Unknown34 => true,
            TaskOpcode.Unknown35 => true,
            TaskOpcode.Unknown36 => true,
            TaskOpcode.CompareBattleCharacterHealthLessThanOrEqual => true,
            TaskOpcode.CompareBattleCharacterHealthPercentLessThanOrEqual => true,
            TaskOpcode.CompareBattleCharacterMagicLessThanOrEqual => true,
            TaskOpcode.CompareBattleCharacterMagicPercentLessThanOrEqual => true,
            TaskOpcode.CompareBattleCharacterHealthPercentInRange => true,
            TaskOpcode.CompareBattleCharacterHealthGreaterThanOrEqual => true,
            TaskOpcode.CompareBattleCharacterHealthPercentGreaterThanOrEqual => true,
            TaskOpcode.CompareStrongpointChild => true,
            TaskOpcode.CompareBattlePartyIsOneUnit => true,
            TaskOpcode.CompareHeroIsNaked => true,
            TaskOpcode.Unknown41 => true,
            TaskOpcode.CompareBattleCharacterHeartCountGreaterThanOrEqual => true,
            TaskOpcode.CompareBattleCharacterHeartCountLessThanOrEqual => true,
            TaskOpcode.Unknown44 => true,
            TaskOpcode.CompareUnknownFlag => true,
            TaskOpcode.CompareWeather => true,
            TaskOpcode.Unknown47 => true,
            TaskOpcode.CompareApproval => true,
            TaskOpcode.CompareBattleCharacterLoyaltyGreaterThanOrEqual => true,
            TaskOpcode.CompareBattleCharacterLoyaltyLessThanOrEqual => true,
            TaskOpcode.Unknown4B => true,
            TaskOpcode.Unknown4C => true,
            TaskOpcode.CompareBattlePartyIsThreeUnits => true,
            TaskOpcode.CompareHasItem => true,
            TaskOpcode.Unknown4F => true,
            TaskOpcode.Unknown50 => true,
            TaskOpcode.Unknown51 => true,
            TaskOpcode.Unknown52 => true,
            TaskOpcode.CompareHasCharacter => true,
            TaskOpcode.NoOperation84 => false,
            TaskOpcode.NoOperation85 => false,
            TaskOpcode.NoOperation86 => false,
            TaskOpcode.NoOperation87 => false,
            TaskOpcode.NoOperation88 => false,
            TaskOpcode.NoOperation89 => false,
            TaskOpcode.NoOperation90 => false,
            TaskOpcode.NoOperation91 => false,
            TaskOpcode.NoOperation92 => false,
            TaskOpcode.NoOperation93 => false,
            TaskOpcode.NoOperation94 => false,
            TaskOpcode.NoOperation95 => false,
            TaskOpcode.AndCount => true,
            TaskOpcode.AndOrAnd => true,
            TaskOpcode.AndAndOrAnd => true,
            TaskOpcode.AndAndAndOr => true,
            TaskOpcode.AndOr => true,
            TaskOpcode.OrOrOrOrOrOrAnd => true,
            TaskOpcode.OrAndOrAndOrAndOr => true,
            TaskOpcode.Or => true,
            TaskOpcode.OrOr => true,
            TaskOpcode.AndAndAndOrOr => true,
            TaskOpcode.AndAndAndAndAndAndOr => true,
            TaskOpcode.AndAndAndAndAndAndAndAndAndAndAndOr => true,
            TaskOpcode.AndAndAndAndAndAndAndAndAndOr => true,
            TaskOpcode.AndAndAndOrOrOr => true,
            TaskOpcode.AndAndAndAndAndOr => true,
            TaskOpcode.AndAndAndAndAndAndOrAnd => true,
            _ => throw new ArgumentOutOfRangeException(nameof(opcode)),
        };

        public static TaskType GetTaskType(this TaskOpcode opcode) => opcode switch
        {
            TaskOpcode.NoOperation0 => TaskType.ProcessingTask,
            TaskOpcode.SetGlobalFlag => TaskType.ProcessingTask,
            TaskOpcode.SetLocalFlag => TaskType.ProcessingTask,
            TaskOpcode.ModifyApproval => TaskType.ProcessingTask,
            TaskOpcode.PlatoonNow => TaskType.ProcessingTask,
            TaskOpcode.ModifyGoth => TaskType.ProcessingTask,
            TaskOpcode.ModifyDays => TaskType.ProcessingTask,
            TaskOpcode.ModifyLoyaltyForBattlePartyLawfulUnits => TaskType.ProcessingTask,
            TaskOpcode.ModifyLoyaltyForBattlePartyNeutralUnits => TaskType.ProcessingTask,
            TaskOpcode.ModifyLoyaltyForBattlePartyChaosUnits => TaskType.ProcessingTask,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterLawfulUnits => TaskType.ProcessingTask,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterNeutralUnits => TaskType.ProcessingTask,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterChaosUnits => TaskType.ProcessingTask,
            TaskOpcode.SetHeroAlignment => TaskType.ProcessingTask,
            TaskOpcode.ResetGlobalFlagsInCategory => TaskType.ProcessingTask,
            TaskOpcode.SetPartyCharacterClan => TaskType.ProcessingTask,
            TaskOpcode.ModifyRosterUnitsInClanLoyalty => TaskType.ProcessingTask,
            TaskOpcode.SetPartyCharacterLoyalty => TaskType.ProcessingTask,
            TaskOpcode.SetStrongpointChild => TaskType.ProcessingTask,
            TaskOpcode.SetHeroClan => TaskType.ProcessingTask,
            TaskOpcode.GetItem => TaskType.ProcessingTask,
            TaskOpcode.Unknown15 => TaskType.ProcessingTask,
            TaskOpcode.Unknown16 => TaskType.ProcessingTask,
            TaskOpcode.Unknown17 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation24 => TaskType.ProcessingTask,
            TaskOpcode.Unknown19 => TaskType.ProcessingTask,
            TaskOpcode.SetPartyAllegiance => TaskType.ProcessingTask,
            TaskOpcode.Unknown1B => TaskType.ProcessingTask,
            TaskOpcode.Unknown1C => TaskType.ProcessingTask,
            TaskOpcode.SetUnknownFlag => TaskType.ProcessingTask,
            TaskOpcode.ResetUnknownFlags => TaskType.ProcessingTask,
            TaskOpcode.SetPartyCharacterClass => TaskType.ProcessingTask,
            TaskOpcode.RemoveItem => TaskType.ProcessingTask,
            TaskOpcode.Unknown21 => TaskType.ProcessingTask,
            TaskOpcode.Unknown22 => TaskType.ProcessingTask,
            TaskOpcode.Unknown23 => TaskType.ProcessingTask,
            TaskOpcode.Unknown24 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation37 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation38 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation39 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation40 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation41 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation42 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation43 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation44 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation45 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation46 => TaskType.ProcessingTask,
            TaskOpcode.NoOperation47 => TaskType.ProcessingTask,
            TaskOpcode.CompareGlobalFlag => TaskType.Invocation,
            TaskOpcode.CompareLocalFlag => TaskType.Invocation,
            TaskOpcode.CompareStrongpoint => TaskType.Invocation,
            TaskOpcode.CompareBattleActiveCharacter => TaskType.Invocation,
            TaskOpcode.Unknown34 => TaskType.Invocation,
            TaskOpcode.Unknown35 => TaskType.Invocation,
            TaskOpcode.Unknown36 => TaskType.Invocation,
            TaskOpcode.CompareBattleCharacterHealthLessThanOrEqual => TaskType.Invocation,
            TaskOpcode.CompareBattleCharacterHealthPercentLessThanOrEqual => TaskType.Invocation,
            TaskOpcode.CompareBattleCharacterMagicLessThanOrEqual => TaskType.Invocation,
            TaskOpcode.CompareBattleCharacterMagicPercentLessThanOrEqual => TaskType.Invocation,
            TaskOpcode.CompareBattleCharacterHealthPercentInRange => TaskType.Invocation,
            TaskOpcode.CompareBattleCharacterHealthGreaterThanOrEqual => TaskType.Invocation,
            TaskOpcode.CompareBattleCharacterHealthPercentGreaterThanOrEqual => TaskType.Invocation,
            TaskOpcode.CompareStrongpointChild => TaskType.Invocation,
            TaskOpcode.CompareBattlePartyIsOneUnit => TaskType.Invocation,
            TaskOpcode.CompareHeroIsNaked => TaskType.Invocation,
            TaskOpcode.Unknown41 => TaskType.Invocation,
            TaskOpcode.CompareBattleCharacterHeartCountGreaterThanOrEqual => TaskType.Invocation,
            TaskOpcode.CompareBattleCharacterHeartCountLessThanOrEqual => TaskType.Invocation,
            TaskOpcode.Unknown44 => TaskType.Invocation,
            TaskOpcode.CompareUnknownFlag => TaskType.Invocation,
            TaskOpcode.CompareWeather => TaskType.Invocation,
            TaskOpcode.Unknown47 => TaskType.Invocation,
            TaskOpcode.CompareApproval => TaskType.Invocation,
            TaskOpcode.CompareBattleCharacterLoyaltyGreaterThanOrEqual => TaskType.Invocation,
            TaskOpcode.CompareBattleCharacterLoyaltyLessThanOrEqual => TaskType.Invocation,
            TaskOpcode.Unknown4B => TaskType.Invocation,
            TaskOpcode.Unknown4C => TaskType.Invocation,
            TaskOpcode.CompareBattlePartyIsThreeUnits => TaskType.Invocation,
            TaskOpcode.CompareHasItem => TaskType.Invocation,
            TaskOpcode.Unknown4F => TaskType.Invocation,
            TaskOpcode.Unknown50 => TaskType.Invocation,
            TaskOpcode.Unknown51 => TaskType.Invocation,
            TaskOpcode.Unknown52 => TaskType.Invocation,
            TaskOpcode.CompareHasCharacter => TaskType.Invocation,
            TaskOpcode.NoOperation84 => TaskType.Invocation,
            TaskOpcode.NoOperation85 => TaskType.Invocation,
            TaskOpcode.NoOperation86 => TaskType.Invocation,
            TaskOpcode.NoOperation87 => TaskType.Invocation,
            TaskOpcode.NoOperation88 => TaskType.Invocation,
            TaskOpcode.NoOperation89 => TaskType.Invocation,
            TaskOpcode.NoOperation90 => TaskType.Invocation,
            TaskOpcode.NoOperation91 => TaskType.Invocation,
            TaskOpcode.NoOperation92 => TaskType.Invocation,
            TaskOpcode.NoOperation93 => TaskType.Invocation,
            TaskOpcode.NoOperation94 => TaskType.Invocation,
            TaskOpcode.NoOperation95 => TaskType.Invocation,
            TaskOpcode.AndCount => TaskType.Expression,
            TaskOpcode.AndOrAnd => TaskType.Expression,
            TaskOpcode.AndAndOrAnd => TaskType.Expression,
            TaskOpcode.AndAndAndOr => TaskType.Expression,
            TaskOpcode.AndOr => TaskType.Expression,
            TaskOpcode.OrOrOrOrOrOrAnd => TaskType.Expression,
            TaskOpcode.OrAndOrAndOrAndOr => TaskType.Expression,
            TaskOpcode.Or => TaskType.Expression,
            TaskOpcode.OrOr => TaskType.Expression,
            TaskOpcode.AndAndAndOrOr => TaskType.Expression,
            TaskOpcode.AndAndAndAndAndAndOr => TaskType.Expression,
            TaskOpcode.AndAndAndAndAndAndAndAndAndAndAndOr => TaskType.Expression,
            TaskOpcode.AndAndAndAndAndAndAndAndAndOr => TaskType.Expression,
            TaskOpcode.AndAndAndOrOrOr => TaskType.Expression,
            TaskOpcode.AndAndAndAndAndOr => TaskType.Expression,
            TaskOpcode.AndAndAndAndAndAndOrAnd => TaskType.Expression,
            _ => throw new ArgumentOutOfRangeException(nameof(opcode)),
        };

        public static int GetSize(this TaskOpcode opcode) => opcode switch
        {
            TaskOpcode.NoOperation0 => 0,
            TaskOpcode.SetGlobalFlag => 3,
            TaskOpcode.SetLocalFlag => 3,
            TaskOpcode.ModifyApproval => 2,
            TaskOpcode.PlatoonNow => 1,
            TaskOpcode.ModifyGoth => 4,
            TaskOpcode.ModifyDays => 1,
            TaskOpcode.ModifyLoyaltyForBattlePartyLawfulUnits => 1,
            TaskOpcode.ModifyLoyaltyForBattlePartyNeutralUnits => 1,
            TaskOpcode.ModifyLoyaltyForBattlePartyChaosUnits => 1,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterLawfulUnits => 1,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterNeutralUnits => 1,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterChaosUnits => 1,
            TaskOpcode.SetHeroAlignment => 1,
            TaskOpcode.ResetGlobalFlagsInCategory => 1,
            TaskOpcode.SetPartyCharacterClan => 3,
            TaskOpcode.ModifyRosterUnitsInClanLoyalty => 2,
            TaskOpcode.SetPartyCharacterLoyalty => 3,
            TaskOpcode.SetStrongpointChild => 2,
            TaskOpcode.SetHeroClan => 1,
            TaskOpcode.GetItem => 2,
            TaskOpcode.Unknown15 => 4,
            TaskOpcode.Unknown16 => 2,
            TaskOpcode.Unknown17 => 1,
            TaskOpcode.NoOperation24 => 2,
            TaskOpcode.Unknown19 => 1,
            TaskOpcode.SetPartyAllegiance => 1,
            TaskOpcode.Unknown1B => 3,
            TaskOpcode.Unknown1C => 1,
            TaskOpcode.SetUnknownFlag => 3,
            TaskOpcode.ResetUnknownFlags => 0,
            TaskOpcode.SetPartyCharacterClass => 3,
            TaskOpcode.RemoveItem => 2,
            TaskOpcode.Unknown21 => 1,
            TaskOpcode.Unknown22 => 1,
            TaskOpcode.Unknown23 => 2,
            TaskOpcode.Unknown24 => 2,
            TaskOpcode.NoOperation37 => 0,
            TaskOpcode.NoOperation38 => 0,
            TaskOpcode.NoOperation39 => 0,
            TaskOpcode.NoOperation40 => 0,
            TaskOpcode.NoOperation41 => 0,
            TaskOpcode.NoOperation42 => 0,
            TaskOpcode.NoOperation43 => 0,
            TaskOpcode.NoOperation44 => 0,
            TaskOpcode.NoOperation45 => 0,
            TaskOpcode.NoOperation46 => 0,
            TaskOpcode.NoOperation47 => 0,
            TaskOpcode.CompareGlobalFlag => 4,
            TaskOpcode.CompareLocalFlag => 4,
            TaskOpcode.CompareStrongpoint => 2,
            TaskOpcode.CompareBattleActiveCharacter => 3,
            TaskOpcode.Unknown34 => 2,
            TaskOpcode.Unknown35 => 4,
            TaskOpcode.Unknown36 => 4,
            TaskOpcode.CompareBattleCharacterHealthLessThanOrEqual => 4,
            TaskOpcode.CompareBattleCharacterHealthPercentLessThanOrEqual => 4,
            TaskOpcode.CompareBattleCharacterMagicLessThanOrEqual => 4,
            TaskOpcode.CompareBattleCharacterMagicPercentLessThanOrEqual => 4,
            TaskOpcode.CompareBattleCharacterHealthPercentInRange => 5,
            TaskOpcode.CompareBattleCharacterHealthGreaterThanOrEqual => 4,
            TaskOpcode.CompareBattleCharacterHealthPercentGreaterThanOrEqual => 4,
            TaskOpcode.CompareStrongpointChild => 3,
            TaskOpcode.CompareBattlePartyIsOneUnit => 2,
            TaskOpcode.CompareHeroIsNaked => 2,
            TaskOpcode.Unknown41 => 2,
            TaskOpcode.CompareBattleCharacterHeartCountGreaterThanOrEqual => 4,
            TaskOpcode.CompareBattleCharacterHeartCountLessThanOrEqual => 4,
            TaskOpcode.Unknown44 => 4,
            TaskOpcode.CompareUnknownFlag => 4,
            TaskOpcode.CompareWeather => 2,
            TaskOpcode.Unknown47 => 3,
            TaskOpcode.CompareApproval => 3,
            TaskOpcode.CompareBattleCharacterLoyaltyGreaterThanOrEqual => 4,
            TaskOpcode.CompareBattleCharacterLoyaltyLessThanOrEqual => 4,
            TaskOpcode.Unknown4B => 3,
            TaskOpcode.Unknown4C => 3,
            TaskOpcode.CompareBattlePartyIsThreeUnits => 2,
            TaskOpcode.CompareHasItem => 3,
            TaskOpcode.Unknown4F => 2,
            TaskOpcode.Unknown50 => 3,
            TaskOpcode.Unknown51 => 3,
            TaskOpcode.Unknown52 => 2,
            TaskOpcode.CompareHasCharacter => 3,
            TaskOpcode.NoOperation84 => 0,
            TaskOpcode.NoOperation85 => 0,
            TaskOpcode.NoOperation86 => 0,
            TaskOpcode.NoOperation87 => 0,
            TaskOpcode.NoOperation88 => 0,
            TaskOpcode.NoOperation89 => 0,
            TaskOpcode.NoOperation90 => 0,
            TaskOpcode.NoOperation91 => 0,
            TaskOpcode.NoOperation92 => 0,
            TaskOpcode.NoOperation93 => 0,
            TaskOpcode.NoOperation94 => 0,
            TaskOpcode.NoOperation95 => 0,
            TaskOpcode.AndCount => 1,
            TaskOpcode.AndOrAnd => 1,
            TaskOpcode.AndAndOrAnd => 1,
            TaskOpcode.AndAndAndOr => 1,
            TaskOpcode.AndOr => 1,
            TaskOpcode.OrOrOrOrOrOrAnd => 1,
            TaskOpcode.OrAndOrAndOrAndOr => 1,
            TaskOpcode.Or => 1,
            TaskOpcode.OrOr => 1,
            TaskOpcode.AndAndAndOrOr => 1,
            TaskOpcode.AndAndAndAndAndAndOr => 1,
            TaskOpcode.AndAndAndAndAndAndAndAndAndAndAndOr => 1,
            TaskOpcode.AndAndAndAndAndAndAndAndAndOr => 1,
            TaskOpcode.AndAndAndOrOrOr => 1,
            TaskOpcode.AndAndAndAndAndOr => 1,
            TaskOpcode.AndAndAndAndAndAndOrAnd => 1,
            _ => throw new ArgumentOutOfRangeException(nameof(opcode)),
        };

        public static (TargetType targetType, ValueType valueType) GetArguments(this TaskOpcode opcode) => opcode switch
        {
            TaskOpcode.SetGlobalFlag => (TargetType.GlobalFlag, ValueType.Int8),
            TaskOpcode.SetLocalFlag => (TargetType.LocalFlag, ValueType.Bool),
            TaskOpcode.ModifyApproval => (TargetType.ApprovalRate, ValueType.Int8),
            TaskOpcode.PlatoonNow => (TargetType.None, ValueType.Int8),
            TaskOpcode.ModifyGoth => (TargetType.None, ValueType.Int32),
            TaskOpcode.ModifyDays => (TargetType.None, ValueType.Int8),
            TaskOpcode.ModifyLoyaltyForBattlePartyLawfulUnits => (TargetType.None, ValueType.Int8),
            TaskOpcode.ModifyLoyaltyForBattlePartyNeutralUnits => (TargetType.None, ValueType.Int8),
            TaskOpcode.ModifyLoyaltyForBattlePartyChaosUnits => (TargetType.None, ValueType.Int8),
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterLawfulUnits => (TargetType.None, ValueType.Int8),
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterNeutralUnits => (TargetType.None, ValueType.Int8),
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterChaosUnits => (TargetType.None, ValueType.Int8),
            TaskOpcode.SetHeroAlignment => (TargetType.None, ValueType.Int8),
            TaskOpcode.ResetGlobalFlagsInCategory => (TargetType.None, ValueType.Int8),
            TaskOpcode.SetPartyCharacterClan => (TargetType.UnknownUInt16, ValueType.Int8),
            TaskOpcode.ModifyRosterUnitsInClanLoyalty => (TargetType.UnknownUInt8, ValueType.Int8),
            TaskOpcode.SetPartyCharacterLoyalty => (TargetType.UnknownUInt16, ValueType.Int8),
            TaskOpcode.SetStrongpointChild => (TargetType.None, ValueType.UInt16),
            TaskOpcode.SetHeroClan => (TargetType.UnknownUInt8, ValueType.None),
            TaskOpcode.GetItem => (TargetType.None, ValueType.UInt16),
            TaskOpcode.Unknown15 => (TargetType.UnknownUInt16, ValueType.Int8),
            TaskOpcode.Unknown16 => (TargetType.None, ValueType.UInt16),
            TaskOpcode.Unknown17 => (TargetType.None, ValueType.Int8),

            TaskOpcode.Unknown19 => (TargetType.None, ValueType.Int8),
            TaskOpcode.SetPartyAllegiance => (TargetType.None, ValueType.UInt8),

            TaskOpcode.Unknown1C => (TargetType.None, ValueType.UInt8),

            TaskOpcode.ResetUnknownFlags => (TargetType.None, ValueType.None),

            TaskOpcode.RemoveItem => (TargetType.None, ValueType.UInt16),
            TaskOpcode.Unknown21 => (TargetType.None, ValueType.UInt8),
            TaskOpcode.Unknown22 => (TargetType.None, ValueType.Int8),
            TaskOpcode.Unknown23 => (TargetType.UnknownUInt16, ValueType.None),
            TaskOpcode.Unknown24 => (TargetType.UnknownUInt16, ValueType.None),

            TaskOpcode.CompareGlobalFlag => (TargetType.GlobalFlag, ValueType.UInt8),
            TaskOpcode.CompareLocalFlag => (TargetType.LocalFlag, ValueType.UInt8),
            TaskOpcode.CompareStrongpoint => (TargetType.None, ValueType.Int8),

            TaskOpcode.CompareBattleActiveCharacter => (TargetType.None, ValueType.UInt16),

            TaskOpcode.Unknown34 => (TargetType.None, ValueType.Int8),
            TaskOpcode.Unknown35 => (TargetType.UnknownUInt16, ValueType.Int8),
            TaskOpcode.Unknown36 => (TargetType.UnknownUInt16, ValueType.Int8),
            TaskOpcode.CompareBattleCharacterHealthLessThanOrEqual => (TargetType.UnknownUInt16, ValueType.Int8),
            TaskOpcode.CompareBattleCharacterHealthPercentLessThanOrEqual => (TargetType.UnknownUInt16, ValueType.Int8),

            TaskOpcode.CompareBattleCharacterHealthGreaterThanOrEqual => (TargetType.UnknownUInt16, ValueType.Int8),
            TaskOpcode.CompareBattleCharacterHealthPercentGreaterThanOrEqual => (TargetType.UnknownUInt16, ValueType.Int8),
            TaskOpcode.CompareStrongpointChild => (TargetType.None, ValueType.Int16),
            TaskOpcode.CompareBattlePartyIsOneUnit => (TargetType.None, ValueType.Int8),
            TaskOpcode.CompareHeroIsNaked => (TargetType.None, ValueType.Int8),
            TaskOpcode.Unknown41 => (TargetType.UnknownUInt8, ValueType.None),
            TaskOpcode.CompareBattleCharacterHeartCountGreaterThanOrEqual => (TargetType.UnknownUInt16, ValueType.UInt8),
            TaskOpcode.CompareBattleCharacterHeartCountLessThanOrEqual => (TargetType.UnknownUInt16, ValueType.UInt8),
            TaskOpcode.Unknown44 => (TargetType.UnknownUInt16, ValueType.Int8),
            TaskOpcode.CompareUnknownFlag => (TargetType.UnknownUInt16, ValueType.Int8),
            TaskOpcode.CompareWeather => (TargetType.None, ValueType.Int8),
            TaskOpcode.Unknown47 => (TargetType.UnknownUInt8, ValueType.Int8),
            TaskOpcode.CompareApproval => (TargetType.ApprovalRate, ValueType.UInt8),
            TaskOpcode.CompareBattleCharacterLoyaltyGreaterThanOrEqual => (TargetType.UnknownUInt16, ValueType.UInt8),

            TaskOpcode.Unknown4B => (TargetType.UnknownUInt16, ValueType.None),
            TaskOpcode.Unknown4C => (TargetType.UnknownUInt16, ValueType.None),
            TaskOpcode.CompareBattlePartyIsThreeUnits => (TargetType.None, ValueType.UInt8),
            TaskOpcode.CompareHasItem => (TargetType.UnknownUInt16, ValueType.None),
            TaskOpcode.Unknown4F => (TargetType.UnknownUInt8, ValueType.None),

            TaskOpcode.Unknown50 => (TargetType.None, ValueType.UInt16),
            TaskOpcode.Unknown51 => (TargetType.None, ValueType.UInt16),
            TaskOpcode.Unknown52 => (TargetType.None, ValueType.UInt8),
            TaskOpcode.CompareHasCharacter => (TargetType.UnknownUInt16, ValueType.None),

            _ => throw new NotSupportedException(),
        };

        internal static InvocationArgumentOrder GetArgumentOrder(this TaskOpcode opcode) => opcode switch
        {
            TaskOpcode.Unknown35 => InvocationArgumentOrder.ValueExpressionTarget,
            TaskOpcode.Unknown36 => InvocationArgumentOrder.ValueExpressionTarget,
            TaskOpcode.CompareBattleCharacterHealthLessThanOrEqual => InvocationArgumentOrder.ValueExpressionTarget,
            TaskOpcode.CompareBattleCharacterHealthPercentLessThanOrEqual => InvocationArgumentOrder.ValueExpressionTarget,

            TaskOpcode.CompareBattleCharacterHealthGreaterThanOrEqual => InvocationArgumentOrder.ValueExpressionTarget,
            TaskOpcode.CompareBattleCharacterHealthPercentGreaterThanOrEqual => InvocationArgumentOrder.ValueExpressionTarget,

            TaskOpcode.CompareBattleCharacterHeartCountGreaterThanOrEqual => InvocationArgumentOrder.ValueExpressionTarget,
            TaskOpcode.CompareBattleCharacterHeartCountLessThanOrEqual => InvocationArgumentOrder.ValueExpressionTarget,
            TaskOpcode.Unknown44 => InvocationArgumentOrder.ValueExpressionTarget,

            TaskOpcode.Unknown47 => InvocationArgumentOrder.ValueExpressionTarget,
            TaskOpcode.CompareApproval => InvocationArgumentOrder.ExpressionTargetValue,
            TaskOpcode.CompareBattleCharacterLoyaltyGreaterThanOrEqual => InvocationArgumentOrder.ValueExpressionTarget,

            TaskOpcode.Unknown4B => InvocationArgumentOrder.ValueExpressionTarget,
            TaskOpcode.Unknown4C => InvocationArgumentOrder.ValueExpressionTarget,

            TaskOpcode.CompareHasItem => InvocationArgumentOrder.ValueExpressionTarget,
            TaskOpcode.Unknown4F => InvocationArgumentOrder.ValueExpressionTarget,

            TaskOpcode.CompareHasCharacter => InvocationArgumentOrder.ValueExpressionTarget,

            _ => InvocationArgumentOrder.TargetExpressionValue,
        };

        public static int GetCallbackAddressPSP(this TaskOpcode opcode) => opcode switch
        {
            TaskOpcode.NoOperation0 => 0x088B6C08,
            TaskOpcode.SetGlobalFlag => 0x088B6C10,
            TaskOpcode.SetLocalFlag => 0x088B6C4C,
            TaskOpcode.ModifyApproval => 0x088B6D04,
            TaskOpcode.PlatoonNow => 0x088B6D7C,
            TaskOpcode.ModifyGoth => 0x088B6E04,
            TaskOpcode.ModifyDays => 0x088B6E80,
            TaskOpcode.ModifyLoyaltyForBattlePartyLawfulUnits => 0x088B707C,
            TaskOpcode.ModifyLoyaltyForBattlePartyNeutralUnits => 0x088B70AC,
            TaskOpcode.ModifyLoyaltyForBattlePartyChaosUnits => 0x088B70DC,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterLawfulUnits => 0x088B71C0,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterNeutralUnits => 0x088B7210,
            TaskOpcode.ModifyLoyaltyForBattlePartyAndRosterChaosUnits => 0x088B7260,
            TaskOpcode.SetHeroAlignment => 0x088B72B0,
            TaskOpcode.ResetGlobalFlagsInCategory => 0x088B739C,
            TaskOpcode.SetPartyCharacterClan => 0x088B7460,
            TaskOpcode.ModifyRosterUnitsInClanLoyalty => 0x088B7524,
            TaskOpcode.SetPartyCharacterLoyalty => 0x088B75DC,
            TaskOpcode.SetStrongpointChild => 0x088B6DD4,
            TaskOpcode.SetHeroClan => 0x088B7668,
            TaskOpcode.GetItem => 0x088B7718,
            TaskOpcode.Unknown15 => 0x088B7984,
            TaskOpcode.Unknown16 => 0x088B79E8,
            TaskOpcode.Unknown17 => 0x088B7A20,
            TaskOpcode.NoOperation24 => 0x088B7A4C,
            TaskOpcode.Unknown19 => 0x088B7A54,
            TaskOpcode.SetPartyAllegiance => 0x088B7A80,
            TaskOpcode.Unknown1B => 0x088B7AA0,
            TaskOpcode.Unknown1C => 0x088B7AF8,
            TaskOpcode.SetUnknownFlag => 0x088B6CC8,
            TaskOpcode.ResetUnknownFlags => 0x088B7B14,
            TaskOpcode.SetPartyCharacterClass => 0x088B7B48,
            TaskOpcode.RemoveItem => 0x088B7750,
            TaskOpcode.Unknown21 => 0x088B7C20,
            TaskOpcode.Unknown22 => 0x088B7C60,
            TaskOpcode.Unknown23 => 0x088B7C98,
            TaskOpcode.Unknown24 => 0x088B7910,
            TaskOpcode.NoOperation37 => 0x088B6C08,
            TaskOpcode.NoOperation38 => 0x088B6C08,
            TaskOpcode.NoOperation39 => 0x088B6C08,
            TaskOpcode.NoOperation40 => 0x088B6C08,
            TaskOpcode.NoOperation41 => 0x088B6C08,
            TaskOpcode.NoOperation42 => 0x088B6C08,
            TaskOpcode.NoOperation43 => 0x088B6C08,
            TaskOpcode.NoOperation44 => 0x088B6C08,
            TaskOpcode.NoOperation45 => 0x088B6C08,
            TaskOpcode.NoOperation46 => 0x088B6C08,
            TaskOpcode.NoOperation47 => 0x088B6C08,
            TaskOpcode.CompareGlobalFlag => 0x088B7CE8,
            TaskOpcode.CompareLocalFlag => 0x088B7D68,
            TaskOpcode.CompareStrongpoint => 0x088B7E74,
            TaskOpcode.CompareBattleActiveCharacter => 0x088B7F34,
            TaskOpcode.Unknown34 => 0x088B7FC0,
            TaskOpcode.Unknown35 => 0x088B8024,
            TaskOpcode.Unknown36 => 0x088B80C0,
            TaskOpcode.CompareBattleCharacterHealthLessThanOrEqual => 0x088B815C,
            TaskOpcode.CompareBattleCharacterHealthPercentLessThanOrEqual => 0x088B81D8,
            TaskOpcode.CompareBattleCharacterMagicLessThanOrEqual => 0x088B827C,
            TaskOpcode.CompareBattleCharacterMagicPercentLessThanOrEqual => 0x088B82F8,
            TaskOpcode.CompareBattleCharacterHealthPercentInRange => 0x088B839C,
            TaskOpcode.CompareBattleCharacterHealthGreaterThanOrEqual => 0x088B8498,
            TaskOpcode.CompareBattleCharacterHealthPercentGreaterThanOrEqual => 0x088B8514,
            TaskOpcode.CompareStrongpointChild => 0x088B7ECC,
            TaskOpcode.CompareBattlePartyIsOneUnit => 0x088B85B8,
            TaskOpcode.CompareHeroIsNaked => 0x088B8630,
            TaskOpcode.Unknown41 => 0x088B86D0,
            TaskOpcode.CompareBattleCharacterHeartCountGreaterThanOrEqual => 0x088B874C,
            TaskOpcode.CompareBattleCharacterHeartCountLessThanOrEqual => 0x088B87CC,
            TaskOpcode.Unknown44 => 0x088B884C,
            TaskOpcode.CompareUnknownFlag => 0x088B7DF4,
            TaskOpcode.CompareWeather => 0x088B88E4,
            TaskOpcode.Unknown47 => 0x088B893C,
            TaskOpcode.CompareApproval => 0x088B89FC,
            TaskOpcode.CompareBattleCharacterLoyaltyGreaterThanOrEqual => 0x088B8A9C,
            TaskOpcode.CompareBattleCharacterLoyaltyLessThanOrEqual => 0x088B8B28,
            TaskOpcode.Unknown4B => 0x088B8BB4,
            TaskOpcode.Unknown4C => 0x088B8C64,
            TaskOpcode.CompareBattlePartyIsThreeUnits => 0x088B8D14,
            TaskOpcode.CompareHasItem => 0x088B8D8C,
            TaskOpcode.Unknown4F => 0x088B8E18,
            TaskOpcode.Unknown50 => 0x088B8E68,
            TaskOpcode.Unknown51 => 0x088B8EF8,
            TaskOpcode.Unknown52 => 0x088B8F88,
            TaskOpcode.CompareHasCharacter => 0x088B9078,
            TaskOpcode.NoOperation84 => 0x088B6C08,
            TaskOpcode.NoOperation85 => 0x088B6C08,
            TaskOpcode.NoOperation86 => 0x088B6C08,
            TaskOpcode.NoOperation87 => 0x088B6C08,
            TaskOpcode.NoOperation88 => 0x088B6C08,
            TaskOpcode.NoOperation89 => 0x088B6C08,
            TaskOpcode.NoOperation90 => 0x088B6C08,
            TaskOpcode.NoOperation91 => 0x088B6C08,
            TaskOpcode.NoOperation92 => 0x088B6C08,
            TaskOpcode.NoOperation93 => 0x088B6C08,
            TaskOpcode.NoOperation94 => 0x088B6C08,
            TaskOpcode.NoOperation95 => 0x088B6C08,
            TaskOpcode.AndCount => 0x088B90FC,
            TaskOpcode.AndOrAnd => 0x088B91C4,
            TaskOpcode.AndAndOrAnd => 0x088B9258,
            TaskOpcode.AndAndAndOr => 0x088B92F8,
            TaskOpcode.AndOr => 0x088B9398,
            TaskOpcode.OrOrOrOrOrOrAnd => 0x088B9420,
            TaskOpcode.OrAndOrAndOrAndOr => 0x088B94E4,
            TaskOpcode.Or => 0x088B95A4,
            TaskOpcode.OrOr => 0x088B9618,
            TaskOpcode.AndAndAndOrOr => 0x088B969C,
            TaskOpcode.AndAndAndAndAndAndOr => 0x088B9754,
            TaskOpcode.AndAndAndAndAndAndAndAndAndAndAndOr => 0x088B9800,
            TaskOpcode.AndAndAndAndAndAndAndAndAndOr => 0x088B98AC,
            TaskOpcode.AndAndAndOrOrOr => 0x088B9958,
            TaskOpcode.AndAndAndAndAndOr => 0x088B9A1C,
            TaskOpcode.AndAndAndAndAndAndOrAnd => 0x088B9AC8,
            _ => throw new ArgumentOutOfRangeException(nameof(opcode)),
        };
    }
}
