[4000]
path = "localize"

# 0 (ja-jp) defined below
1 = { path = "en-us", redirect = "4000.0" }
2 = { path = "fr-fr", redirect = "4000.0" }
3 = { path = "de-de", redirect = "4000.0" }
4 = { path = "es-es", redirect = "4000.0" }
5 = { path = "zh-cn", redirect = "4000.0" }
6 = { path = "zh-tw", redirect = "4000.0" }
7 = { path = "ko-kr", redirect = "4000.0" }

[4000.0]
path = "ja-jp"

0.path  = "arms_text"
1.path  = "commodity_text"
2.path  = "common"
3.path  = "character_name"
4.path  = "death_dialogue"
5.path  = "effect_text"
6.path  = "gameover_condition"
7.path  = "mapobj_text"
8.path  = "other_text"
9.path  = "panel_text"
10.path = "select_text"
11.path = "seq_text_data"
12.path = "skill_status_text"
13.path = "skill_text"
14.path = "speech"
15.path = "spell"
16.path = "status_text"
17.path = "union_text"
18.path = "unit_name_0"
19.path = "unit_name_1"
20.path = "unit_name_2"
21.path = "unit_name_3"
22.path = "unit_name_4"
23.path = "unit_name_5"
24.path = "victory_condition"
25.path = "wr_term"
26.path = "warning_text"
27.path = "anchor_text"
28.path = "battle_text"
29.path = "chapter_text"
30.path = "chara_text"
31.path = "class_text_data"
32.path = "credit_text_name"
33.path = "credit_text"
34.path = "current_affairs_text"
35.path = "diva_text"
36.path = "guidecap_text"
37.path = "guideope_text"
38.path = "auction"
39.path = "choice"
40.path = "command"
41.path = "confirm"
42.path = "shop_dialogue"
43.path = "dismiss"
44.path = "extra"
45.path = "guest_menu"
46.path = "guide"
47.path = "information"
48.path = "item_equipping"
49.path = "loyalty"
50.path = "misc_message"
51.path = "modal"
52.path = "order"
53.path = "revolt"
54.path = "select_help"
55.path = "stronghold"
56.path = "tag"
57.path = "warning"
58.path = "rumor"
59.path = "scenario_C1"
60.path = "scenario_C2a"
61.path = "scenario_C2b"
62.path = "scenario_C3a"
63.path = "scenario_C3b"
64.path = "scenario_C3c"
65.path = "scenario_C4"
66.path = "scenario_C4sub"
67.path = "scenario_dlc"
68.path = "scenario_ep"
69.path = "tarot_text"
70.path = "buffcard_text"
71.path = "battle_task"
