[900]
path = "event/chapter"

[900.10]
path = "chapter_1"

0_1.path = "C1.pgrs"
0_2.path = "C1.invk"
0_3.path = "C1.task"
0_6.path = "C1_localize.xlc"

[900.11]
path = "chapter_2/chaos" # chapter_2a

0_1.path = "C2a.pgrs"
0_2.path = "C2a.invk"
0_3.path = "C2a.task"
0_6.path = "C2a_localize.xlc"

[900.12]
path = "chapter_2/law" # chapter_2b

0_1.path = "C2b.pgrs"
0_2.path = "C2b.invk"
0_3.path = "C2b.task"
0_6.path = "C2b_localize.xlc"

[900.13]
path = "chapter_3/neutral" # chapter_3a

0_1.path = "C3a.pgrs"
0_2.path = "C3a.invk"
0_3.path = "C3a.task"
0_6.path = "C3a_localize.xlc"

[900.14]
path = "chapter_3/chaos" # chapter_3b

0_1.path = "C3b.pgrs"
0_2.path = "C3b.invk"
0_3.path = "C3b.task"
0_6.path = "C3b_localize.xlc"

[900.15]
path = "chapter_3/law" # chapter_3c

0_1.path = "C3c.pgrs"
0_2.path = "C3c.invk"
0_3.path = "C3c.task"
0_6.path = "C3c_localize.xlc"

[900.16]
path = "chapter_4"

0_1.path = "C4.pgrs"
0_2.path = "C4.invk"
0_3.path = "C4.task"
0_6.path = "C4_localize.xlc"
0_7.path = "C4sub_localize.xlc"

[900.17]
path = "chapter_ep"

0_1.path = "EP.pgrs"
0_2.path = "EP.invk"
0_3.path = "EP.task"
0_6.path = "EP_localize.xlc"

[900.18]
path = "chapter_dlc"

0_1.path = "DLC.pgrs"
0_2.path = "DLC.invk"
0_3.path = "DLC.task"
0_6.path = "DLC_localize.xlc"
0_7.path = "C4sub_localize.xlc"

[900.20]
path = "event_data"

1.path = "character_name_localize.xlc"

3.path = "global_flags.xlc"
4.path = "unknown_flags.xlc"

6.path = "death_agony_localize.xlc"

7.path = "death_agony.invk" # assumed
8.path = "death_agony.task" # assumed
9.path = "death_agony.script" # assumed

10.path = "battle_start.pgrs" # assumed
11.path = "battle_start.invk" # assumed
12.path = "battle_start.task" # assumed
13.path = "battle_start.script"
